export const MOCK_PREDICTIONS = [
  {
    id: '1',
    title: "ARIRANG will debut at #1 on the Billboard 200 in its first week (March 20, 2026)",
    description: "All 7 members are back. ARMY mobilisation infrastructure is at peak capacity and pre-order numbers are already signalling history. A #1 Billboard 200 debut is the floor, not the ceiling. The question is by how wide a margin.",
    category: 'Market Analysis',
    member: 'Group',
    status: 'active',
    confidence_avg: 94,
    vote_count: 487,
    created_at: '2026-03-05T10:00:00Z',
    profiles: { display_name: 'Timeline Architect', username: 'tl_architect' },
  },
  {
    id: '2',
    title: "The ARIRANG lead single will hit #1 on Billboard Hot 100 on release day",
    description: "Every major analysis of BTS's Hot 100 history points to a day-one #1 as the baseline. Post-military reunion + the most anticipated BTS release since Map of the Soul: 7 = a streaming surge unlike anything since Dynamite.",
    category: 'Entertainment',
    member: 'Group',
    status: 'active',
    confidence_avg: 89,
    vote_count: 412,
    created_at: '2026-03-05T11:00:00Z',
    profiles: { display_name: 'Prophet Zero', username: 'prophet_zero' },
  },
  {
    id: '3',
    title: "ARIRANG will outsell Map of the Soul: 7 first-week — breaking BTS's own record",
    description: "Post-military reunion fever plus a 3-year group album drought equals the most commercially primed release in BTS history. Sales analysts are calling this a record-breaking cycle before a single note has dropped.",
    category: 'Market Analysis',
    member: 'Group',
    status: 'active',
    confidence_avg: 76,
    vote_count: 341,
    created_at: '2026-03-04T09:00:00Z',
    profiles: { display_name: 'Signal Spotter Nine', username: 'signal_nine' },
  },
  {
    id: '4',
    title: "BTS will announce a world tour within 30 days of ARIRANG's release",
    description: "Called it. The BTS WORLD TOUR: ARIRANG is officially confirmed — 79 shows across 34 cities and 5 continents. April 2026 to March 2027. The largest tour by any South Korean artist. The signals were all there. 💜",
    category: 'Entertainment',
    member: 'Group',
    status: 'resolved_correct',
    confidence_avg: 82,
    vote_count: 298,
    created_at: '2026-03-06T14:00:00Z',
    profiles: { display_name: 'Timeline Architect', username: 'tl_architect' },
  },
  {
    id: '5',
    title: "At least one ARIRANG track will feature a surprise Western artist collaboration",
    description: "The GQ interview hinted at creative experiences during their individual eras. HYBE's Western label network plus each member's solo-era connections make a hidden feature statistically likely. Watch the tracklist drop carefully.",
    category: 'Soft Conspiracy',
    member: 'Group',
    status: 'active',
    confidence_avg: 58,
    vote_count: 189,
    created_at: '2026-03-03T16:00:00Z',
    profiles: { display_name: 'The Archivist', username: 'the_archivist' },
  },
  {
    id: '6',
    title: "Jungkook's solo contribution to ARIRANG will be the most-streamed individual track",
    description: "JK's global streaming dominance — established with 'Seven' and 'Standing Next to You' — makes him the statistical frontrunner for highest solo streams within any BTS group project. His global solo fanbase has only grown.",
    category: 'Market Analysis',
    member: 'Jungkook',
    status: 'active',
    confidence_avg: 67,
    vote_count: 228,
    created_at: '2026-03-02T12:00:00Z',
    profiles: { display_name: 'Observation Deck', username: 'obs_deck' },
  },
  {
    id: '7',
    title: "Jin will generate the most viral solo moment from ARIRANG promotions",
    description: "After his discharge, Jin's cultural re-entry has been extraordinary. The emotional weight of his reunion with members, combined with his natural screen presence, makes him the most statistically likely breakout across all ARIRANG promo content.",
    category: 'Body Language',
    member: 'Jin',
    status: 'active',
    confidence_avg: 71,
    vote_count: 176,
    created_at: '2026-03-01T10:00:00Z',
    profiles: { display_name: 'Signal Spotter Nine', username: 'signal_nine' },
  },
  {
    id: '8',
    title: "V's visual direction will set a new aesthetic benchmark for ARIRANG's era",
    description: "Kim Taehyung's deepening role in BTS's visual identity — accelerated through his LAYOVER era — suggests ARIRANG's art direction carries his unmistakable imprint. Expect gallery-level concepts crossing into mainstream cultural conversation.",
    category: 'Cultural Trends',
    member: 'V',
    status: 'active',
    confidence_avg: 78,
    vote_count: 152,
    created_at: '2026-03-03T15:00:00Z',
    profiles: { display_name: 'The Archivist', username: 'the_archivist' },
  },
  {
    id: '9',
    title: "RM's ARIRANG lyrics will be the most cited and critically analysed of the album",
    description: "Namjoon's lyrical density has been a constant conversation starter. Post-military reflection layered with his art world immersion will produce his most textured writing yet. Critics and fans will unpack his verses for months.",
    category: 'Cultural Trends',
    member: 'RM',
    status: 'active',
    confidence_avg: 73,
    vote_count: 139,
    created_at: '2026-03-04T11:00:00Z',
    profiles: { display_name: 'Prophet Zero', username: 'prophet_zero' },
  },
  {
    id: '10',
    title: "Jimin's ARIRANG vocal will be the most covered song on social media within 2 weeks of release",
    description: "The viral architecture of Jimin solo moments — from Serendipity to Like Crazy — combined with his growing global fanbase points to a massive fan-cover cycle within the first two weeks. The melody will live rent-free everywhere.",
    category: 'Entertainment',
    member: 'Jimin',
    status: 'active',
    confidence_avg: 69,
    vote_count: 163,
    created_at: '2026-03-05T13:00:00Z',
    profiles: { display_name: 'Timeline Architect', username: 'tl_architect' },
  },
  {
    id: '11',
    title: "Suga has a production credit on ARIRANG under the Agust D alias",
    description: "Yoongi's known pattern of embedding solo-credited production into group album cycles — and HYBE's recent teaser content analysis — suggests an Agust D-credited track is embedded somewhere in the ARIRANG tracklist.",
    category: 'Soft Conspiracy',
    member: 'Suga',
    status: 'active',
    confidence_avg: 54,
    vote_count: 116,
    created_at: '2026-03-06T09:00:00Z',
    profiles: { display_name: 'Signal Spotter Nine', username: 'signal_nine' },
  },
  {
    id: '12',
    title: "J-Hope will bring the most theatrically staged live performance to ARIRANG promotions",
    description: "Hoseok's 'Jack in the Box' and Lollapalooza era redefined his performance identity as a solo act. That creative ambition does not get shelved when he reunites with BTS — it elevates the entire group's live concept.",
    category: 'Cultural Trends',
    member: 'J-Hope',
    status: 'active',
    confidence_avg: 66,
    vote_count: 108,
    created_at: '2026-03-02T16:00:00Z',
    profiles: { display_name: 'Observation Deck', username: 'obs_deck' },
  },
  {
    id: '13',
    title: "ARIRANG will be the best-charting K-pop album ever on the UK Official Albums Chart",
    description: "UK ARMY organisation has matured significantly since the Love Yourself era. Combined with BTS's mainstream crossover in Britain — accelerated by their Wembley and Hyde Park shows — ARIRANG has the conditions to set a new K-pop ceiling.",
    category: 'Market Analysis',
    member: 'Group',
    status: 'active',
    confidence_avg: 61,
    vote_count: 97,
    created_at: '2026-03-01T08:00:00Z',
    profiles: { display_name: 'The Archivist', username: 'the_archivist' },
  },
  {
    id: '14',
    title: "BTS fully reunited as a group before end of 2025",
    description: "Called it. All members completed military service on schedule. The reunion wasn't just confirmed — it was celebrated globally, setting the stage for the ARIRANG era. This prediction aged perfectly. 방탄소년단 💜",
    category: 'Entertainment',
    member: 'Group',
    status: 'resolved_correct',
    confidence_avg: 91,
    vote_count: 634,
    created_at: '2025-06-13T08:00:00Z',
    profiles: { display_name: 'Timeline Architect', username: 'tl_architect' },
  },
  {
    id: '15',
    title: 'BTS WORLD TOUR: ARIRANG will gross over $1 billion — becoming K-pop\'s first billion-dollar tour',
    description: '79 shows across 34 cities with in-the-round stadium staging and post-military demand at its absolute peak. The average ticket price, scaled across capacity, projects a figure no K-pop act has ever touched. This is a historic economic event.',
    category: 'Market Analysis',
    member: 'Group',
    status: 'active',
    confidence_avg: 71,
    vote_count: 334,
    created_at: '2026-03-09T10:00:00Z',
    profiles: { display_name: 'Timeline Architect', username: 'tl_architect' },
  },
  {
    id: '16',
    title: 'The Seoul opening night will set a new attendance record for a single concert in Korea',
    description: 'Seoul World Cup Stadium at full in-the-round capacity, first show of the entire world tour, home crowd after military service — the emotional and commercial conditions for a historic Korean attendance record are all aligned.',
    category: 'Market Analysis',
    member: 'Group',
    status: 'active',
    confidence_avg: 78,
    vote_count: 201,
    created_at: '2026-03-09T11:00:00Z',
    profiles: { display_name: 'Prophet Zero', username: 'prophet_zero' },
  },
  {
    id: '17',
    title: 'Wembley Stadium will be the most talked-about single show of the entire world tour',
    description: 'Wembley carries a mythological weight for BTS — the 2019 Love Yourself shows were a landmark moment. Returning post-military for 4 nights at Wembley Stadium is the emotional centrepiece of the European leg and culturally the most resonant moment of the global run.',
    category: 'Cultural Trends',
    member: 'Group',
    status: 'active',
    confidence_avg: 64,
    vote_count: 178,
    created_at: '2026-03-09T12:00:00Z',
    profiles: { display_name: 'The Archivist', username: 'the_archivist' },
  },
]

export const MOCK_LEADERBOARD = [
  { id: '1', display_name: 'Timeline Architect', username: 'tl_architect', correct_predictions: 35, total_predictions: 41, title: 'Timeline Architect' },
  { id: '2', display_name: 'Prophet Zero', username: 'prophet_zero', correct_predictions: 28, total_predictions: 35, title: 'Timeline Architect' },
  { id: '3', display_name: 'The Archivist', username: 'the_archivist', correct_predictions: 19, total_predictions: 26, title: 'High Accuracy Analyst' },
  { id: '4', display_name: 'Signal Spotter Nine', username: 'signal_nine', correct_predictions: 12, total_predictions: 19, title: 'Cultural Prophet' },
  { id: '5', display_name: 'Observation Deck', username: 'obs_deck', correct_predictions: 8, total_predictions: 14, title: 'Cultural Prophet' },
  { id: '6', display_name: 'Pattern Witness', username: 'pat_witness', correct_predictions: 5, total_predictions: 9, title: 'Signal Spotter' },
  { id: '7', display_name: 'Quiet Observer', username: 'quiet_obs', correct_predictions: 4, total_predictions: 8, title: 'Signal Spotter' },
  { id: '8', display_name: 'Emergence Scout', username: 'emg_scout', correct_predictions: 2, total_predictions: 5, title: 'Emerging Theorist' },
]

export const MOCK_STATS = {
  total_analysts: 1847,
  total_predictions: 4312,
  avg_accuracy: 71,
  album_drop: 'March 20, 2026',
  days_until_drop: 13,
}

export const CATEGORIES = [
  'All',
  'Market Analysis',
  'Body Language',
  'Soft Conspiracy',
  'Cultural Trends',
  'Entertainment',
]

export const BTS_MEMBERS = [
  { id: 'all', label: 'All', emoji: '💜' },
  { id: 'Group', label: 'Group', emoji: '🎶' },
  { id: 'RM', label: 'RM', emoji: '🎤' },
  { id: 'Jin', label: 'Jin', emoji: '🌸' },
  { id: 'Suga', label: 'Suga', emoji: '🎹' },
  { id: 'J-Hope', label: 'J-Hope', emoji: '☀️' },
  { id: 'Jimin', label: 'Jimin', emoji: '✨' },
  { id: 'V', label: 'V', emoji: '🎨' },
  { id: 'Jungkook', label: 'JK', emoji: '🐰' },
]

export function getAnalystTitle(correctPredictions) {
  if (correctPredictions >= 30) return 'Timeline Architect'
  if (correctPredictions >= 15) return 'High Accuracy Analyst'
  if (correctPredictions >= 7) return 'Cultural Prophet'
  if (correctPredictions >= 3) return 'Signal Spotter'
  return 'Emerging Theorist'
}
