export const NEWS_ARTICLES = [
  {
    id: 'n1',
    source: 'GQ',
    source_url: 'https://www.gq.com',
    title: 'BTS Reply To Fans Online',
    excerpt: 'BTS (방탄소년단) go online to answer the internet\'s questions ahead of their ARIRANG comeback. The members address fan theories, inside jokes, and long-running questions from across their career.',
    youtube_id: 'PKoaxkX4wGw',
    url: 'https://youtu.be/PKoaxkX4wGw?si=rEd-8ltLZfY9qWI7',
    published_at: '2026-03-08T09:00:00Z',
    category: 'Interview',
    featured: true,
    tags: ['GQ', 'interview', 'ARIRANG', 'comeback'],
  },
  {
    id: 'n2',
    source: 'Yahoo Entertainment',
    source_url: 'https://yahoo.com/entertainment',
    title: "BTS Respond to Fans' Questions Online Ahead of 'Arirang' Album",
    excerpt: "Throughout the episode, the members address a mix of fan theories, inside jokes and long-running questions. BTS's chemistry post-military is electric — the banter is at an all-time high.",
    url: 'https://yahoo.com',
    youtube_id: null,
    published_at: '2026-03-08T07:00:00Z',
    category: 'News',
    featured: false,
    tags: ['Yahoo', 'ARIRANG', 'fan questions'],
  },
  {
    id: 'n3',
    source: 'Billboard',
    source_url: 'https://billboard.com',
    title: "BTS's 'ARIRANG' Is Already Setting Pre-Order Records Before Release",
    excerpt: "With 11 days until the March 20 release, ARIRANG has surpassed 3 million pre-orders globally — shattering the record set by Map of the Soul: 7 in its first pre-order week.",
    url: 'https://billboard.com',
    youtube_id: null,
    published_at: '2026-03-09T11:00:00Z',
    category: 'Market Data',
    featured: false,
    tags: ['Billboard', 'pre-orders', 'ARIRANG', 'records'],
  },
  {
    id: 'n4',
    source: 'Rolling Stone',
    source_url: 'https://rollingstone.com',
    title: "Why BTS's Military Return Marks a New Era for K-Pop's Global Dominance",
    excerpt: "The cultural infrastructure ARMY built during the hiatus is unprecedented. BTS returning with a unified album isn't just a musical event — it's a case study in fanbase-as-movement.",
    url: 'https://rollingstone.com',
    youtube_id: null,
    published_at: '2026-03-07T14:00:00Z',
    category: 'Analysis',
    featured: false,
    tags: ['Rolling Stone', 'comeback', 'military', 'K-pop'],
  },
  {
    id: 'n5',
    source: 'Weverse Magazine',
    source_url: 'https://weverseshop.io',
    title: "Inside ARIRANG: RM on What the Album Title Really Means",
    excerpt: "Namjoon opens up about choosing the title ARIRANG — the ancient Korean folk song — for the group's reunion album. 'It felt like the most honest thing we could say after everything.'",
    url: 'https://weverseshop.io',
    youtube_id: null,
    published_at: '2026-03-06T10:00:00Z',
    category: 'Interview',
    featured: false,
    tags: ['Weverse', 'RM', 'ARIRANG', 'meaning'],
  },
  {
    id: 'n6',
    source: 'NME',
    source_url: 'https://nme.com',
    title: "BTS Spotted at Multiple London Venues — World Tour Rumours Intensify",
    excerpt: "Sources close to HYBE's live division report venue capacity assessments across London, New York, Seoul, and Tokyo. No official announcement yet, but the infrastructure signals are unmistakable.",
    url: 'https://nme.com',
    youtube_id: null,
    published_at: '2026-03-05T16:00:00Z',
    category: 'Rumour',
    featured: false,
    tags: ['NME', 'world tour', 'rumour', 'HYBE'],
  },
]

export const EVENTS = [
  {
    id: 'e1',
    title: 'ARIRANG Album Drop',
    date: '2026-03-20',
    time: '00:00 KST',
    type: 'release',
    description: 'BTS\'s full group comeback album ARIRANG releases globally. Midnight KST. Stream from all platforms.',
    url: null,
    confirmed: true,
  },
  {
    id: 'e2',
    title: 'BTS × GQ — "Reply To Fans" (Live on YouTube)',
    date: '2026-03-08',
    time: 'Published',
    type: 'media',
    description: 'GQ drops their BTS fan-questions video — members answer internet theories, inside jokes, and long-running mysteries ahead of ARIRANG.',
    url: 'https://youtu.be/PKoaxkX4wGw?si=rEd-8ltLZfY9qWI7',
    confirmed: true,
  },
  {
    id: 'e3',
    title: 'ARIRANG Listening Party — Weverse Live',
    date: '2026-03-20',
    time: '23:00 KST',
    type: 'live',
    description: 'Expected Weverse live session with members reacting to ARIRANG fan responses in real time. Unconfirmed but patterns from past album drops are consistent.',
    url: null,
    confirmed: false,
  },
  {
    id: 'e4',
    title: 'BTS on Late Night TV — US Promo Run (Rumoured)',
    date: '2026-03-24',
    time: 'TBC',
    type: 'media',
    description: 'Multiple sources report BTS are booked for at least two US late-night appearances in the week following the ARIRANG release. No official confirmation yet.',
    url: null,
    confirmed: false,
  },
  {
    id: 'e5',
    title: 'World Tour Announcement (Expected Window)',
    date: '2026-04-10',
    time: 'TBC',
    type: 'announcement',
    description: 'Based on historical HYBE tour announcement patterns and current venue pre-booking signals, analysts predict a world tour drop within 21 days of the album release.',
    url: null,
    confirmed: false,
  },
]

export const FAN_DISCUSSIONS = [
  {
    id: 'fd1',
    platform: 'Reddit',
    platform_icon: '🔴',
    title: '[THEORY] ARIRANG tracklist leak analysis — what the cryptic teasers actually mean',
    url: 'https://reddit.com/r/bangtan',
    community: 'r/bangtan',
    upvotes: '12.4k',
    comments: 847,
    posted_at: '2026-03-07T18:00:00Z',
  },
  {
    id: 'fd2',
    platform: 'Reddit',
    platform_icon: '🔴',
    title: 'GQ interview breakdown — every detail the members dropped about the album',
    url: 'https://reddit.com/r/bangtan',
    community: 'r/bangtan',
    upvotes: '9.2k',
    comments: 1203,
    posted_at: '2026-03-08T12:00:00Z',
  },
  {
    id: 'fd3',
    platform: 'Weverse',
    platform_icon: '💜',
    title: 'ARMY Theory Hub: Hidden ARIRANG clues in past Run BTS episodes',
    url: 'https://weverse.io',
    community: 'BTS Weverse',
    upvotes: '34.1k',
    comments: 4209,
    posted_at: '2026-03-06T09:00:00Z',
  },
  {
    id: 'fd4',
    platform: 'Twitter/X',
    platform_icon: '🐦',
    title: '#ARIRANG trending — ARMY compile every pre-release clue in one thread',
    url: 'https://x.com/search?q=%23ARIRANG',
    community: '#ARIRANG',
    upvotes: '88.7k',
    comments: 21000,
    posted_at: '2026-03-09T08:00:00Z',
  },
  {
    id: 'fd5',
    platform: 'Twitter/X',
    platform_icon: '🐦',
    title: 'BTS members\' solo-era sounds dissected: what each member brings to ARIRANG',
    url: 'https://x.com',
    community: 'ARMY Space',
    upvotes: '41.2k',
    comments: 8340,
    posted_at: '2026-03-08T20:00:00Z',
  },
]

export const TRACKLIST_SPECULATION = [
  {
    track: 1,
    title: 'ARIRANG (아리랑)',
    type: 'Title Track',
    confidence: 97,
    notes: 'Confirmed. The title track — a reimagining of the traditional Korean folk song built for a 2026 sonic landscape.',
    member: 'Group',
    confirmed: true,
  },
  {
    track: 2,
    title: 'Untitled Group Track',
    type: 'Group',
    confidence: 90,
    notes: 'Expected high-energy group performance track. Likely the pre-release single based on HYBE\'s standard release pattern.',
    member: 'Group',
    confirmed: false,
  },
  {
    track: 3,
    title: 'RM Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'Namjoon\'s solo contribution is expected to be lyric-heavy and reflective — drawing on his post-military art world experiences.',
    member: 'RM',
    confirmed: false,
  },
  {
    track: 4,
    title: 'Jin Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'Jin\'s comeback solo. Post-discharge fan signals are pointing toward an emotive ballad that matches his "The Astronaut" trajectory.',
    member: 'Jin',
    confirmed: false,
  },
  {
    track: 5,
    title: 'Suga Solo / Agust D Feature',
    type: 'Solo',
    confidence: 78,
    notes: 'Whether credited as Suga or Agust D, Yoongi\'s track is expected to be the most sonically daring cut on the album.',
    member: 'Suga',
    confirmed: false,
  },
  {
    track: 6,
    title: 'J-Hope Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'Post-Lollapalooza J-Hope energy. Expected to carry the most festival-ready, high-production live concept of any track.',
    member: 'J-Hope',
    confirmed: false,
  },
  {
    track: 7,
    title: 'Jimin Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'Jimin\'s vocal showcase. If it follows the "Like Crazy" or "Set Me Free Pt. 2" arc, this will be a major streaming event.',
    member: 'Jimin',
    confirmed: false,
  },
  {
    track: 8,
    title: 'V Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'Expected to be the most cinematic track on the record. V\'s LAYOVER era aesthetic suggests something deeply visual and jazz-adjacent.',
    member: 'V',
    confirmed: false,
  },
  {
    track: 9,
    title: 'Jungkook Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'JK\'s solo cut is projected to be the highest-streamed individual track. Global pop appeal combined with his post-GOLDEN sound evolution.',
    member: 'Jungkook',
    confirmed: false,
  },
  {
    track: 10,
    title: 'Hidden Western Feature',
    type: 'Feature',
    confidence: 54,
    notes: 'Soft conspiracy. HYBE\'s Western label partnerships and member solo-era connections make a hidden collab statistically plausible.',
    member: 'Group',
    confirmed: false,
  },
]

export const MEMBER_COLORS = {
  RM: { bg: 'bg-blue-500/20', text: 'text-blue-300', border: 'border-blue-500/30' },
  Jin: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
  Suga: { bg: 'bg-gray-500/20', text: 'text-gray-300', border: 'border-gray-400/30' },
  'J-Hope': { bg: 'bg-orange-500/20', text: 'text-orange-300', border: 'border-orange-500/30' },
  Jimin: { bg: 'bg-rose-500/20', text: 'text-rose-300', border: 'border-rose-500/30' },
  V: { bg: 'bg-teal-500/20', text: 'text-teal-300', border: 'border-teal-500/30' },
  Jungkook: { bg: 'bg-purple-500/20', text: 'text-purple-300', border: 'border-purple-500/30' },
  Group: { bg: 'bg-white/10', text: 'text-white/80', border: 'border-white/20' },
}
