export const NEWS_ARTICLES = [
  {
    id: 'n1',
    source: 'HYBE',
    source_url: 'https://hybecorp.com',
    title: 'BTS 5th Studio Album ARIRANG — Official Announcement & Release Date',
    excerpt: 'HYBE confirms BTS will release their 5th studio album ARIRANG on March 20, 2026 at 1PM KST. All seven members contributed to the record following the completion of their mandatory military service.',
    url: 'https://hybecorp.com',
    youtube_id: null,
    category: 'News',
    featured: true,
    published_at: '2026-01-15T09:00:00Z',
    tags: ['ARIRANG', 'album', 'official'],
  },
  {
    id: 'n2',
    source: 'GQ Korea',
    source_url: 'https://gq.co.kr',
    title: 'BTS: "ARIRANG Is the Album We Were Born to Make"',
    excerpt: 'In an exclusive cover story, all seven BTS members sit down with GQ Korea to discuss the meaning of ARIRANG, their military service, and why this album feels like a rebirth for the group.',
    url: 'https://gq.co.kr',
    youtube_id: null,
    category: 'Interview',
    featured: false,
    published_at: '2026-02-10T10:00:00Z',
    tags: ['interview', 'GQ', 'ARIRANG'],
  },
  {
    id: 'n3',
    source: 'Billboard',
    source_url: 'https://billboard.com',
    title: 'BTS ARIRANG Pre-Save Breaks 24-Hour Streaming Record — 18M in First Day',
    excerpt: 'Before the album has even dropped, ARIRANG has shattered pre-save records across Spotify and Apple Music, accumulating 18 million pre-saves within 24 hours of the link going live.',
    url: 'https://billboard.com',
    youtube_id: null,
    category: 'Market Data',
    featured: false,
    published_at: '2026-02-20T14:00:00Z',
    tags: ['records', 'streaming', 'charts'],
  },
  {
    id: 'n4',
    source: 'Weverse Magazine',
    source_url: 'https://weversemagzine.com',
    title: 'RM on ARIRANG: "I Wrote My Verses in the Mountains"',
    excerpt: 'In a long-form Weverse Magazine piece, RM opens up about writing his contributions to ARIRANG during late-night sessions near his base during military service, drawing on traditional Korean poetry.',
    url: 'https://weversemagazine.com',
    youtube_id: null,
    category: 'Interview',
    featured: false,
    published_at: '2026-02-25T08:00:00Z',
    tags: ['RM', 'interview', 'lyrics'],
  },
  {
    id: 'n5',
    source: 'HYBE',
    source_url: 'https://hybecorp.com',
    title: 'BTS World Tour ARIRANG — 79 Shows, 34 Cities, 5 Continents Confirmed',
    excerpt: 'BTS and HYBE officially announce the ARIRANG World Tour running April 2026 through March 2027, making it the largest concert tour ever undertaken by a South Korean artist.',
    url: 'https://btsworldtourofficial.com/',
    youtube_id: null,
    category: 'News',
    featured: false,
    published_at: '2026-03-01T10:00:00Z',
    tags: ['tour', 'world tour', 'announcement'],
  },
  {
    id: 'n6',
    source: 'Rolling Stone',
    source_url: 'https://rollingstone.com',
    title: 'Why ARIRANG Could Be the Biggest K-Pop Album of All Time',
    excerpt: 'Rolling Stone breaks down the cultural weight of BTS returning with a full group album named after Korea\'s most iconic folk song, and why industry analysts are predicting historic first-week numbers.',
    url: 'https://rollingstone.com',
    youtube_id: null,
    category: 'Analysis',
    featured: false,
    published_at: '2026-03-05T12:00:00Z',
    tags: ['analysis', 'charts', 'ARIRANG'],
  },
  {
    id: 'n7',
    source: 'Weverse',
    source_url: 'https://weverse.io',
    title: 'Jungkook Drops Pre-Album Single "AURORA" — Listen Now',
    excerpt: 'Ahead of the full ARIRANG album release, Jungkook releases the pre-release solo track AURORA, described by the member as "a letter written from the other side of service." The track debuted at #1 on Melon within minutes.',
    url: 'https://weverse.io',
    youtube_id: null,
    category: 'News',
    featured: false,
    published_at: '2026-03-07T13:00:00Z',
    tags: ['Jungkook', 'AURORA', 'pre-release'],
  },
  {
    id: 'n8',
    source: 'AllKPop',
    source_url: 'https://allkpop.com',
    title: 'ARIRANG Track List Teaser Sparks Fan Theories — 13 Tracks, Two Features Hinted',
    excerpt: 'A partial track list image released via Weverse has sent ARMY into overdrive. Fans have spotted what appears to be two feature credits, and a track titled "한강 (Han River)" is already being tipped as a standout.',
    url: 'https://allkpop.com',
    youtube_id: null,
    category: 'Analysis',
    featured: false,
    published_at: '2026-03-08T16:00:00Z',
    tags: ['tracklist', 'theories', 'features'],
  },
]

export const EVENTS = [
  {
    id: 'e1',
    title: 'BTS × GQ — "Reply To Fans" (YouTube)',
    date: '2026-03-08',
    time: 'Published',
    type: 'media',
    description: 'GQ releases their BTS fan-questions video — all 7 members answer internet theories, inside jokes, and long-running mysteries ahead of ARIRANG.',
    url: 'https://youtu.be/PKoaxkX4wGw?si=rEd-8ltLZfY9qWI7',
    confirmed: true,
  },
  {
    id: 'e2',
    title: 'ARIRANG Album Release',
    date: '2026-03-20',
    time: '13:00 KST',
    type: 'release',
    description: 'BTS 5th studio album ARIRANG drops worldwide at 1PM KST / midnight EST. Available on all streaming platforms.',
    url: null,
    confirmed: true,
  },
  {
    id: 'e3',
    title: 'Music Bank Comeback Stage',
    date: '2026-03-21',
    time: '17:00 KST',
    type: 'live',
    description: 'BTS expected to perform the ARIRANG title track live for the first time on KBS Music Bank the day after release.',
    url: null,
    confirmed: false,
  },
  {
    id: 'e4',
    title: 'ARIRANG Weverse Live — Member Reactions',
    date: '2026-03-20',
    time: '23:00 KST',
    type: 'live',
    description: 'Expected Weverse live session with members reacting to ARMY responses to ARIRANG in real time. Pattern consistent with past album drops.',
    url: 'https://weverse.io',
    confirmed: false,
  },
  {
    id: 'e5',
    title: 'BTS US Late-Night TV Promo Run',
    date: '2026-03-24',
    time: 'TBC',
    type: 'media',
    description: 'Multiple sources report BTS are booked for US late-night appearances in the week following ARIRANG release. No official confirmation yet.',
    url: null,
    confirmed: false,
  },
  {
    id: 'e6',
    title: 'BTS World Tour ARIRANG — Seoul Night 1',
    date: '2026-04-18',
    time: '19:00 KST',
    type: 'tour',
    description: 'Opening night of the BTS World Tour ARIRANG at Jamsil Olympic Stadium, Seoul. The largest production in BTS tour history.',
    url: 'https://btsworldtourofficial.com/',
    confirmed: true,
  },
  {
    id: 'e7',
    title: 'BTS World Tour ARIRANG — Seoul Night 2',
    date: '2026-04-19',
    time: '19:00 KST',
    type: 'tour',
    description: 'Second Seoul night at Jamsil Olympic Stadium. Sold out within 30 minutes of tickets going live.',
    url: 'https://btsworldtourofficial.com/',
    confirmed: true,
  },
  {
    id: 'e8',
    title: 'BTS World Tour ARIRANG — Tokyo Dome Night 1',
    date: '2026-05-08',
    time: '18:00 JST',
    type: 'tour',
    description: 'BTS open their Japan leg at Tokyo Dome. Part of a 4-night run across Tokyo and Osaka.',
    url: 'https://btsworldtourofficial.com/',
    confirmed: true,
  },
  {
    id: 'e9',
    title: 'BTS World Tour ARIRANG — London Wembley',
    date: '2026-07-10',
    time: '19:30 BST',
    type: 'tour',
    description: 'BTS headline Wembley Stadium as part of their European leg. One of 12 European shows across 7 countries.',
    url: 'https://btsworldtourofficial.com/',
    confirmed: true,
  },
  {
    id: 'e10',
    title: 'BTS World Tour ARIRANG — New York MetLife Night 1',
    date: '2026-08-14',
    time: '19:30 EDT',
    type: 'tour',
    description: 'North America leg opens at MetLife Stadium, New Jersey. 4-night New York run before moving to LA, Chicago, and more.',
    url: 'https://btsworldtourofficial.com/',
    confirmed: true,
  },
]

export const FAN_DISCUSSIONS = [
  {
    id: 'fd1',
    platform: 'Reddit',
    platform_icon: '🔴',
    title: '[THEORY] ARIRANG tracklist leak analysis — what the cryptic teasers actually mean',
    url: 'https://reddit.com/r/bangtan',
    community: 'r/bangtan',
    upvotes: '12.4k',
    comments: 847,
    posted_at: '2026-03-07T18:00:00Z',
  },
  {
    id: 'fd2',
    platform: 'Reddit',
    platform_icon: '🔴',
    title: 'GQ interview breakdown — every detail the members dropped about the album',
    url: 'https://reddit.com/r/bangtan',
    community: 'r/bangtan',
    upvotes: '9.2k',
    comments: 1203,
    posted_at: '2026-03-08T12:00:00Z',
  },
  {
    id: 'fd3',
    platform: 'Weverse',
    platform_icon: '💜',
    title: 'ARMY Theory Hub: Hidden ARIRANG clues in past Run BTS episodes',
    url: 'https://weverse.io',
    community: 'BTS Weverse',
    upvotes: '34.1k',
    comments: 4209,
    posted_at: '2026-03-06T09:00:00Z',
  },
  {
    id: 'fd4',
    platform: 'Twitter/X',
    platform_icon: '🐦',
    title: '#ARIRANG trending — ARMY compile every pre-release clue in one thread',
    url: 'https://x.com/search?q=%23ARIRANG',
    community: '#ARIRANG',
    upvotes: '88.7k',
    comments: 21000,
    posted_at: '2026-03-09T08:00:00Z',
  },
  {
    id: 'fd5',
    platform: 'Twitter/X',
    platform_icon: '🐦',
    title: 'BTS members\' solo-era sounds dissected: what each member brings to ARIRANG',
    url: 'https://x.com',
    community: 'ARMY Space',
    upvotes: '41.2k',
    comments: 8340,
    posted_at: '2026-03-08T20:00:00Z',
  },
]

export const TRACKLIST_SPECULATION = [
  {
    track: 1,
    title: 'ARIRANG (아리랑)',
    type: 'Title Track',
    confidence: 97,
    notes: 'Confirmed. The title track — a reimagining of the traditional Korean folk song built for a 2026 sonic landscape.',
    member: 'Group',
    confirmed: true,
  },
  {
    track: 2,
    title: 'Untitled Group Track',
    type: 'Group',
    confidence: 90,
    notes: 'Expected high-energy group performance track. Likely the pre-release single based on HYBE\'s standard release pattern.',
    member: 'Group',
    confirmed: false,
  },
  {
    track: 3,
    title: 'RM Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'Namjoon\'s solo contribution is expected to be lyric-heavy and reflective — drawing on his post-military art world experiences.',
    member: 'RM',
    confirmed: false,
  },
  {
    track: 4,
    title: 'Jin Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'Jin\'s comeback solo. Post-discharge fan signals are pointing toward an emotive ballad that matches his "The Astronaut" trajectory.',
    member: 'Jin',
    confirmed: false,
  },
  {
    track: 5,
    title: 'Suga Solo / Agust D Feature',
    type: 'Solo',
    confidence: 78,
    notes: 'Whether credited as Suga or Agust D, Yoongi\'s track is expected to be the most sonically daring cut on the album.',
    member: 'Suga',
    confirmed: false,
  },
  {
    track: 6,
    title: 'J-Hope Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'Post-Lollapalooza J-Hope energy. Expected to carry the most festival-ready, high-production live concept of any track.',
    member: 'J-Hope',
    confirmed: false,
  },
  {
    track: 7,
    title: 'Jimin Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'Jimin\'s vocal showcase. If it follows the "Like Crazy" or "Set Me Free Pt. 2" arc, this will be a major streaming event.',
    member: 'Jimin',
    confirmed: false,
  },
  {
    track: 8,
    title: 'V Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'Expected to be the most cinematic track on the record. V\'s LAYOVER era aesthetic suggests something deeply visual and jazz-adjacent.',
    member: 'V',
    confirmed: false,
  },
  {
    track: 9,
    title: 'Jungkook Solo',
    type: 'Solo',
    confidence: 85,
    notes: 'JK\'s solo cut is projected to be the highest-streamed individual track. Global pop appeal combined with his post-GOLDEN sound evolution.',
    member: 'Jungkook',
    confirmed: false,
  },
  {
    track: 10,
    title: 'Hidden Western Feature',
    type: 'Feature',
    confidence: 54,
    notes: 'Soft conspiracy. HYBE\'s Western label partnerships and member solo-era connections make a hidden collab statistically plausible.',
    member: 'Group',
    confirmed: false,
  },
]

export const MEMBER_COLORS = {
  RM: { bg: 'bg-blue-500/20', text: 'text-blue-300', border: 'border-blue-500/30' },
  Jin: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
  Suga: { bg: 'bg-gray-500/20', text: 'text-gray-300', border: 'border-gray-400/30' },
  'J-Hope': { bg: 'bg-orange-500/20', text: 'text-orange-300', border: 'border-orange-500/30' },
  Jimin: { bg: 'bg-rose-500/20', text: 'text-rose-300', border: 'border-rose-500/30' },
  V: { bg: 'bg-teal-500/20', text: 'text-teal-300', border: 'border-teal-500/30' },
  Jungkook: { bg: 'bg-purple-500/20', text: 'text-purple-300', border: 'border-purple-500/30' },
  Group: { bg: 'bg-white/10', text: 'text-white/80', border: 'border-white/20' },
}
